### ISSUE TITLE
Usage of the clj-pdf with the compojure-api

### ISSUE THREAD

**Issue by Freyr666** [luminus-framework/luminus#167] opened 2016-11-22 11:58 UTC
Hi. I'm trying to return a pdf file as an answer to a GET request. I'm using compojure sweet api, here are the samples of my code:

```
(defn generate-report [out]
  (pdf/pdf
   [{:header "Test"}
    [:paragraph "Hello"]]
   out))

(defn write-response [report-bytes]
  (with-open [in (java.io.ByteArrayInputStream. report-bytes)]
    (-> (resp/response in)
        (resp/header "Content-Disposition" "filename=report.pdf")
        (resp/header "Content-Length" (count report-bytes))
        (resp/content-type "application/pdf"))))

(defn pdf-response [pdf-data]
  (try
    (let [out (java.io.ByteArrayOutputStream.)]
      (generate-report out)
      (write-response (.toByteArray out)))
    (catch Exception ex
      (http-resp/ok {:error (.getMessage ex)}))))

```

```
(context "/var/report" []
           :tags ["the report api"]

           (GET "/:test" [] 
                :path-params [test :- String]
                :summary  "pdf report"
                (report/pdf-response test))))
```

But both swagger-ui and curl return plain text answer, containing pdf file payload. I'm expecting to get the save file dialog. What have i done wrong?

**Comment by yogthos** [comment] 2016-11-22 13:36
I'm actually not able to reproduce the issue, I've created a new project and added the following:

```clojure
(ns myapp.routes.services
  (:require [ring.util.http-response :refer :all]
            [compojure.api.sweet :refer :all]
            [schema.core :as s]
            [clj-pdf.core :as pdf]
            [ring.util.response :as resp]))

(defn generate-report [out]
  (pdf/pdf
   [{:header "Test"}
    [:paragraph "Hello"]]
   out))

(defn write-response [report-bytes]
  (with-open [in (java.io.ByteArrayInputStream. report-bytes)]
    (-> (resp/response in)
        (resp/header "Content-Disposition" "filename=report.pdf")
        (resp/header "Content-Length" (count report-bytes))
        (resp/content-type "application/pdf"))))

(defn pdf-response [pdf-data]
  (try
    (let [out (java.io.ByteArrayOutputStream.)]
      (generate-report out)
      (write-response (.toByteArray out)))
    (catch Exception ex
      (ok {:error (.getMessage ex)}))))

(defapi service-routes
  {:swagger {:ui "/swagger-ui"
             :spec "/swagger.json"
             :data {:info {:version "1.0.0"
                           :title "Sample API"
                           :description "Sample Services"}}}}
 (context "/var/report" []
            :tags ["the report api"]

            (GET "/:test" []
                 :path-params [test :- String]
                 :summary  "pdf report"
                 (pdf-response test))))
```

I'm able to browse to `localhost:3000/var/report/foo` and see the PDF report. I can also use the swagger UI, and see the response body:

```
%PDF-1.4
%����
2 0 obj
<</Filter/FlateDecode/Length 153>>stream
x�uO�
1��+r\]5e�
>�&�\��Tߴ]�$�L�d&���h9���D����7X�	8��"�F+�z�U�=:���w�L�W�I�������_�M딖���4�M3"��TW@�X$�F���(��H��W���e6�U{�H8
endstream
endobj
4 0 obj
<</Contents 2 0 R/Type/Page/Resources<</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]/Font<</F1 1 0 R>>>>/Parent 3 0 R/MediaBox[0 0 595 842]>>
endobj
1 0 obj
<</Subtype/Type1/Type/Font/BaseFont/Helvetica/Encoding/WinAnsiEncoding>>
endobj
3 0 obj
<</Kids[4 0 R]/Type/Pages/Count 1/ITXT(4.2.0)>>
endobj
5 0 obj
<</Type/Catalog/Pages 3 0 R>>
```

**Comment by Freyr666** [comment] 2016-11-22 13:49
>I'm able to browse to localhost:3000/var/report/foo and see the PDF report. I can also use the swagger UI, and see the response body:

Yeah, i'm getting the same. Shouldn't browser open the save file dialog with the swagger-ui instead of showing the file payload, or should i write some logic on the frontend side to provide file saving option?

**Comment by yogthos** [comment] 2016-11-22 14:35
Ah ok, sounds like you got the original issue resolved then. Swagger-ui showing the payload is expected as it just streams the result back. Browsers will handle the response differently depending on how the MIME type is setup on the client. For example, Chrome and Firefox can both view the PDF inline. You'd have to handle the response on the client if you'd want a specific behavior.

Sounds like we can close the issue then?

**Comment by Freyr666** [comment] 2016-11-22 14:37
Yes, indeed. Thank you very much.

**Closed** 2016-11-22 17:35 UTC
